printWidth: 120
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'all'
bracketSpacing: false
jsxBracketSameLine: false
arrowParens: 'avoid'
proseWrap: 'preserve'
endOfLine: 'lf'
overrides:
  - files: 'README.md'
    options:
      printWidth: 70
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.yml'
    options:
      tabWidth: 2
